### ISSUE TITLE
Create Profile 

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-chip-shop-pp5#23]
[Epic: 2](https://github.com/EdelCorbett/the-chip-shop-pp5/milestone/2)
As a **customer** I can **create a profile** so that **i can review order history and personal information**

**Acceptance Criteria**

1. Customer can create a profile
2. Customer can view order history 
3. Customer can edit personal information 
4. Customer can delete profile

**Task**

- [x] Create Profile page 
- [x] oder history 
- [x] edit profile button
- [x] delete profile button
