### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-chip-shop-pp5#3]
[Epic: 1 ](https://github.com/EdelCorbett/the-chip-shop/milestone/1)
As a Developer I can Deploy project early so that I can continually test the application during development

**Acceptance Criteria**

1. Deployed application on Heroku

**Task**

- [x] Create new app in Heroku
- [x] Add config vars in settings
- [x] Create Procfile for gunicorn
- [x] Add requirments.txt
- [x] Deploy to heroku
